# Changes here will be overwritten by Copier
# DO NOT MANUALLY MODIFY THIS FILE
_commit: v0.1.0
_src_path: https://github.com/calliope-project/data-module-template.git
author_email: i.ruizmanuel@tudelft.nl
author_family_name: Ruiz Manuel
author_given_name: Ivan
github_org: calliope-project
license: Apache-2.0
module_description: A module to create arbitrary regional boundary datasets for energy
    systems modelling
module_long_name: clio - Geo-boundaries module
module_short_name: geo_boundaries_module
readthedocs: false
