# Module settings that users cannot modify.
resources:
  automatic:
    # Links for automatically downloaded files
    dummy_readme: "https://raw.githubusercontent.com/calliope-project/clio/refs/heads/main/README.md"
  overture_release: "2025-01-22.0"
nuts:
  epsg: 3035  # will be converted later to the user-requested epsg
