# A minimal example of how to configure this module
crs:
  projected: "epsg:3857"
  geographic: "epsg:4326"
countries:
  DNK:
    subtype: "1"
    source: "nuts"
    resolution: 01M
    year: 2024
  GBR:
    subtype: "country"
    source: "overture"
  NLD:
    subtype: "0"
    source: "gadm"
  BEL:
    subtype: "country"
    source: "overture"
  CHE:
    subtype: "country"
    source: "overture"
  ESP:
    subtype: "2"
    source: "nuts"
    resolution: 01M
    year: 2024
