# A minimal example of how to configure this module
buffer: 500  # EPSG:3857 is in meters
crs:
  projected: "epsg:3857"
  geographic: "epsg:4326"
countries:
  DNK:
    subtype: "1"
    source: "gadm"
  GBR:
    subtype: "country"
    source: "overture"
  NLD:
    subtype: "2"
    source: "gadm"
  BEL:
    subtype: "country"
    source: "overture"
  CHE:
    subtype: "country"
    source: "overture"
  ESP:
    subtype: "2"
    source: "nuts"
    resolution: 20M
    year: 2003
