# A minimal example of how to configure this module
countries:
  - name: "DNK"
    subtype: "country"
  - name: "GBR"
    subtype: "country"
  - name: "NLD"
    subtype: "country"
  - name: "BEL"
    subtype: "country"
