# A minimal example of how to configure this module
countries:
  - country_id: "DNK"
    subtype: "country"
    source: "overture"
  - country_id: "GBR"
    subtype: "country"
    source: "overture"
  - country_id: "NLD"
    subtype: "country"
    source: "overture"
  - country_id: "BEL"
    subtype: "country"
    source: "overture"
  - country_id: "CHE"
    subtype: "country"
    source: "overture"
