# Check for changes in the upstream template. If changes are found, an issue is opened.
name: Template check.
on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour

jobs:
  copier-update:
    uses: calliope-project/data-module-template/.github/workflows/template-check-version.yml@latest
